name: umiuni2d_media_flutter
description: A new Flutter project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  umiuni2d_media:
    git:
      url: https://github.com/kyorohiro/umiuni2d_media.git
flutter:
  plugin:
    androidPackage: net.umiuni2d.umiuni2dmediaflutter
    pluginClass: Umiuni2dMediaFlutterPlugin
